name: gastos_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Acesso à API do Google Sheets
  googleapis: ^13.1.0
  googleapis_auth: ^1.4.0
  http: ^0.13.6


  intl: ^0.18.1
  notifications: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/credentials.json
