name: gastos_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  
  # Gerenciamento de estado com Cubit
  flutter_bloc: ^8.1.3

  # Manipulação de datas
  intl: ^0.18.1

  # Armazenamento local
  shared_preferences: ^2.2.2

  # Acesso à API do Google Sheets
  googleapis: ^13.1.0
  googleapis_auth: ^1.4.0
  http: ^0.13.6

  # Permissões (para notificações, leitura de notificações)
  permission_handler: ^11.3.1

  # Notificações locais
  flutter_local_notifications: ^17.1.0

  # Leitura de notificações
  receive_sharing_intent: ^1.4.5+2

  # UI
  equatable: ^2.0.5
  uuid: ^4.2.2 # para gerar IDs únicos (útil para despesas)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
